# Generated by Django 4.0.2 on 2022-02-02 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_product_images'),
        ('images', '0003_productimage_alter_image_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
