# Generated by Django 4.0.2 on 2022-02-02 11:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_plural', models.CharField(max_length=255, verbose_name='Название мн.ч.')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('slug_plural', models.SlugField(unique=True, verbose_name='Слаг мн.ч.')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
                ('article', models.CharField(max_length=255, verbose_name='Артикул')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('discount', models.FloatField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)], verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_plural', models.CharField(max_length=255, verbose_name='Название мн.ч.')),
                ('slug', models.SlugField(blank=True, verbose_name='Слаг')),
                ('slug_plural', models.SlugField(blank=True, verbose_name='Слаг мн.ч.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
    ]
