# Generated by Django 4.0.2 on 2022-02-02 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ManyToManyField(through='images.Category_Images', to='images.Image', verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Катеория'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(through='images.Product_Images', to='images.Image', verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='images',
            field=models.ManyToManyField(blank=True, through='images.SubCategory_Images', to='images.Image', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
        ),
    ]
