# Generated by Django 4.0.2 on 2022-02-02 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_images_product_category_product_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='subCategories',
            field=models.ManyToManyField(through='catalog.Category_SubCategory', to='catalog.SubCategory', verbose_name='Подкатегории'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='categories',
            field=models.ManyToManyField(through='catalog.Category_SubCategory', to='catalog.Category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category_subcategory',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
        ),
        migrations.AddField(
            model_name='category_subcategory',
            name='subCategoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.subcategory'),
        ),
    ]
