# Generated by Django 4.0.2 on 2022-02-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_image_options'),
        ('catalog', '0005_product_indexpageshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(through='images.Product_Images', to='images.Image', verbose_name='Изображения'),
        ),
    ]
